### ISSUE TITLE
Missing Tables for Transferfields Warehouse, TimeSheet

### ISSUE THREAD

**Issue by pri-kise** [Companial/CompanialCop#1]
Some tables are missing for the transferfields check:
https://github.com/Companial/CompanialCop/blob/9c050399fa36541e74e4a2c25162969c45bc8364/Design/Rule0027AnalyzeTransferField.cs#L426C1-L426C38

Table "Warehouse Activity Header" is transferred to
 - "Registered Whse. Activity Hdr."
 - "Registered Invt. Movement Hdr."
 - "Posted Invt. Pick Header"
 - "Posted Invt. Put-away Header
 

Check out `CreatePostedActivHeader` and `CreatePostedActivLine` (for the lines) in `codeunit 7324 "Whse.-Activity-Post"`.
Check out `CreateRegActivHeader` and `CreateRegActivLine` in `codeunit 7307 "Whse.-Activity-Register"`.

And the TimeSheet Tables are missing:
Check out procedure `MoveTimeSheetToArchive` in `codeunit 950 "Time Sheet Management"`

Related Discussion on such a CodeCop for the BCLinterCop: https://github.com/StefanMaron/BusinessCentral.LinterCop/discussions/137

**Comment by tinestaric** [comment]
@pri-kise 
Thanks for spotting this. As mentioned in the LinterCop issue, I'll be moving this rule to LinterCop in the upcoming weeks, and I think we should add all the missing pairs there.

**Comment by tinestaric** [comment]
The rule has been merged to LinterCop, any additional changes should be fixed there.
